# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500, null=True)),
                ('size', models.IntegerField()),
                ('hash_md5', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
